name: Build static Qt

on:
  push:
    tags:
      - '*' # Only match all tags, uncomment if needed

permissions:
  contents: write

jobs:
  build: # 请确保作业有名称
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          path: release
          merge-multiple: true
      - uses: softprops/action-gh-release@v2
        with:
          files: release/*
