name: Build static Qt

on:
  push:
    tags:
#      - '*-*' # Only tags with build number
permissions:
  contents: write

jobs:
  runs-on: ubuntu-latest
  needs: build
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/download-artifact@v4
      with:
        path: release
        merge-multiple: true
    - uses: softprops/action-gh-release@v2
      with:
        files: release/*

    - name: Shorthand tags
      run: |
        git config --global user.email "27856297+dependabot-preview[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git tag -d v$QT_VERSION || true
        git tag v$QT_VERSION -m v$QT_VERSION
        git push -f origin v$QT_VERSION
        git tag -d v${QT_VERSION%.*} || true
        git tag v${QT_VERSION%.*} -m v${QT_VERSION%.*}
        git push -f origin v${QT_VERSION%.*}