name: Build static Qt

on:  # 确保 on 之后没有多余空行或内容
  push:
    tags:
      - '*'  # 此行是一个注释，确保格式正确

permissions:
  contents: write

jobs:  # 确保这里没有打错
  build_job:  # 确保每个作业都有名称
    runs-on: ubuntu-latest
    steps:  # 确保这里没有打错
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          path: release
          merge-multiple: true
      - uses: softprops/action-gh-release@v2
        with:
          files: release/*

      - name: Shorthand tags
        run: |
          git config --global user.email "your_email@example.com"
          git config --global user.name "your-username"
          git tag -d v$QT_VERSION || true
          git tag v$QT_VERSION -m v$QT_VERSION
          git push -f origin v$QT_VERSION
          git tag -d v${QT_VERSION%.*} || true
          git tag v${QT_VERSION%.*} -m v${QT_VERSION%.*}
          git push -f origin v${QT_VERSION%.*}
