name: Build static Qt

on:
  push:
    tags:
#      - '*-*' # Only tags with build number
permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest ]
        include:
          - os: windows-latest
            os-caption: windows
          - os: macos-latest
            os-caption: macos

    runs-on: ${{matrix.os}}

    env:
      QT_VERSION: 6.9

    steps:
      - uses: seanmiddleditch/gha-setup-ninja@v5
      - name: Clone Qt repo
        run: |
          git clone https://code.qt.io/qt/qt5.git qt -b '${{env.QT_VERSION}}'
          cd qt
          perl init-repository.pl -f --module-subset=qtbase  #所有模块

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1
        if: contains(matrix.os, 'windows')

      - name: Build Qt (Windows)
        if: contains(matrix.os, 'windows')
        env:
          CL: /MP # Build with multiple processes
          #https://github.com/Fsu0413/Fs-scripts/blob/master/Compile/lib/qtCompile/conf.lua
          #https://github.com/qt/qtbase/blob/dev/cmake/configure-cmake-mapping.md
          # “^” 符号是 Windows 批处理脚本中的换行符,在 PowerShell 中，您可以使用 `（反引号）作为续行符。
        run: |
          mkdir qt_build                                         
          cd qt_build                                           
           ..\qt\configure.bat   -confirm-license -GNinja       `                                      `
           -DCMAKE_INSTALL_PREFIX="../qt_static"                `
           -DCMAKE_BUILD_TYPE=Release                           `
           -DBUILD_SHARED_LIBS=OFF                              `
           -DFEATURE_static_runtime=ON                          `
           -DFEATURE_optimize_size=ON                           `
           -DFEATURE_cxx20=ON                                   `
           -DBUILD_WITH_PCH=ON                                  `
           -DQT_BUILD_EXAMPLES=ON                               `
           -DQT_INSTALL_EXAMPLES_SOURCES=ON                     `
           -DFEATURE_pkg_config=OFF                             `
           -DQT_BUILD_EXAMPLES=OFF                              `
           -DQT_BUILD_TESTS=OFF                                 `
           -DFEATURE_relocatable=ON                             `
           -DFEATURE_doubleconversion=ON                        `
           -DFEATURE_system_doubleconversion=OFF                `
           -DFEATURE_system_zlib=OFF                            `
           -DFEATURE_system_pcre2=OFF                           `
           -DFEATURE_icu=OFF                                    `
           -DFEATURE_opengl_dynamic=ON                          `
           -DFEATURE_ssl=ON                                     `
           -DFEATURE_openssl=OFF                                `
           -DFEATURE_schannel=ON                                `
           -DFEATURE_sql_sqlite=ON                              `
           -DFEATURE_sql_=ON                                    `
           -DFEATURE_sql_odbc=ON                                `
           -DFEATURE_gif=ON                                     `
           -DFEATURE_ico=ON                                     `
           -DFEATURE_png=ON                                     `
           -DFEATURE_jpeg=ON                                    `
           -DFEATURE_system_sqlite=OFF                          `
           -DBUILD_qtgrpc=OFF                                   `
           -DBUILD_qtwebengine=ON                               `
           -DFEATURE_force_system_libs=ON                       `
           -DFEATURE_accessibility=ON                           
           cmake --build . --parallel 4                         
           cmake --install .                                     

      - name: Build Qt (macOS)
        if: contains(matrix.os, 'macos')
        run: |
          mkdir qt_build
          cd qt_build
          ../qt/configure -static -release -optimize-size -prefix "../qt_static" -no-feature-accessibility -- -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"
          cmake --build . --parallel 3
          cmake --install .

      - name: Package binaries
        run: |
          7z a qt-${{env.QT_VERSION}}-static-${{matrix.os-caption}}.zip qt_static

      - uses: actions/upload-artifact@v4
        with:
          name: qt-static-${{matrix.os-caption}}
          path: qt-*.zip

