name: Build static Qt

on:
  push:
    tags:
#      - '*-*' # Only tags with build number
permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest ]
        include:
          - os: windows-latest
            os-caption: windows
          - os: macos-latest
            os-caption: macos

    runs-on: ${{matrix.os}}

    env:
      QT_VERSION: 6.9

    steps:
      - uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Clone Qt repo
        run: |
          git clone https://code.qt.io/qt/qt5.git qt -b '${{env.QT_VERSION}}'
          cd qt
          perl init-repository.pl -f --module-subset=qtbase

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1
        if: contains(matrix.os, 'windows')

      - name: Build Qt (Windows)
        if: contains(matrix.os, 'windows')
        #        env: https://forum.qt.io/topic/156752/qt6-7-compile-failed-from-source-in-windows11/3
        #          CL: /MP # Build with multiple processes
        #        您看到的链接错误是由于缺少库或缺少元器件的库造成的。
        #似乎与此报告非常相似。确保您的源代码树在稳定分支上包含浏览器引擎的良好副本。
        #
        #这种事情也可能是由 source 上的并行构建引起的，其中依赖项没有被完全捕获：它不按顺序构建一些东西并失败。
        #如果你再次运行 ninja，也许是几次，结果会发生变化吗？
        #如果运行，结果会发生变化吗？ninja -j 1
        run: |
          mkdir qt_build
          cd qt_build
          ..\qt\configure.bat -release -static -static-runtime -optimize-size -prefix "..\qt_static" -no-feature-accessibility
          cmake --build . --parallel 4
          cmake --install .

      - name: Build Qt (macOS)
        if: contains(matrix.os, 'macos')
        run: |
          mkdir qt_build
          cd qt_build
          ../qt/configure -static -release -optimize-size -prefix "../qt_static" -no-feature-accessibility -- -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"
          cmake --build . --parallel 3
          cmake --install .

      - name: Package binaries
        run: |
          7z a qt-${{env.QT_VERSION}}-static-${{matrix.os-caption}}.zip qt_static

      - uses: actions/upload-artifact@v4
        with:
          name: qt-static-${{matrix.os-caption}}
          path: qt-*.zip

